### ISSUE TITLE
Design workflow to manage ODFE certs on EKS cluster

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-kubernetes#111]
This issue will track the design of a workflow to manage the creation of certs compatible with a ODFE deployment.

## Tasks

- [ ] Generate root CA beforehand and store it as a secret
- [ ] Generate cert for filebeat on-demand with an initContainer and save to a volume
- [ ] Run Wazuh container with root CA from secret and filebeat cert from volume

**Comment by xr09** [comment]
I'm currently working on a simpler approach using a `kustomization.yml` to preload the certs as secrets and then using these on the cluster. Since the Elastic cluster is not meant to scale automatically then those certs will be loaded at first, the wazuh workers only need certs for filebeat which can be included in the preload step as well.

**Comment by xr09** [comment]
The workflow to follow will be to preload certs and elastic config files as secret and ConfigMaps:

First would be to generate the certificates using the `generate-opendistro-certs.yml`:

`docker-compose -f generate-opendistro-certs.yml run --rm generator`

This should render certs on a folder `odfe_ssl_certs` which later will be used from the `kustomization.yml`.

```yaml
secretGenerator:
  - name: odfe-ssl-certs
    files:
      - ./odfe_ssl_certs/node1.key
      - ./odfe_ssl_certs/node1.pem
      - ./odfe_ssl_certs/node2.key
      - ./odfe_ssl_certs/node2.pem
      - ./odfe_ssl_certs/node3.key
      - ./odfe_ssl_certs/node3.pem
      - ./odfe_ssl_certs/filebeat.key
      - ./odfe_ssl_certs/filebeat.pem
```

To load the Elastic cluster config files a configMapGenerator will be used:

```yaml
configMapGenerator:
  - name: elastic-odfe-conf
    files:
      - elastic_stack/elasticsearch/elastic_conf/*.yml
```

This will create one configMap containing every file inside this folder.

**Comment by xr09** [comment]
### Current status

Managed to deploy the complete 4.0 cluster with a single-node elasticsearch, certificates are being loaded with secretGenerator through the kustomization.yml.

These are the services currently running:
- 1 Wazuh master node
- 2 Wazuh worker nodes
- 1 odfe node
- 1 kibana odfe node

![Screenshot_20201105_193108](https://user-images.githubusercontent.com/1380243/98281769-777ded00-1f9d-11eb-8f45-c02e37c7e66c.png)

#### kustomization.yml
<details>
  <summary>Click to expand</summary>
  
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

secretGenerator:
  - name: odfe-ssl-certs
    files:
      - ./odfe_ssl_certs/root-ca.pem
      - ./odfe_ssl_certs/node1.key
      - ./odfe_ssl_certs/node1.pem
      - ./odfe_ssl_certs/node2.key
      - ./odfe_ssl_certs/node2.pem
      - ./odfe_ssl_certs/node3.key
      - ./odfe_ssl_certs/node3.pem
      - ./odfe_ssl_certs/filebeat.key
      - ./odfe_ssl_certs/filebeat.pem

configMapGenerator:
  - name: elastic-odfe-conf
    files:
      - elastic_stack/elasticsearch/elastic_conf/elasticsearch-node1.yml
      - elastic_stack/elasticsearch/elastic_conf/elasticsearch-node2.yml
      - elastic_stack/elasticsearch/elastic_conf/elasticsearch-node3.yml
      - elastic_stack/elasticsearch/elastic_conf/internal_users.yml

configMapGenerator:
  - name: wazuh-conf
    files:
      - wazuh_managers/wazuh_conf/master.conf
      - wazuh_managers/wazuh_conf/worker.conf

# resources to apply
resources:
  - base/wazuh-ns.yaml

  - secrets/wazuh-api-cred-secret.yaml
  - secrets/wazuh-authd-pass-secret.yaml
  - secrets/wazuh-cluster-key-secret.yaml
  - secrets/elastic-cred-secret.yaml

  - wazuh_managers/wazuh-cluster-svc.yaml
  - wazuh_managers/wazuh-master-svc.yaml
  - wazuh_managers/wazuh-workers-svc.yaml
  - wazuh_managers/wazuh-master-sts.yaml
  - wazuh_managers/wazuh-worker-sts.yaml

  - elastic_stack/elasticsearch/elasticsearch-svc.yaml
  - elastic_stack/elasticsearch/single-node/elasticsearch-api-svc.yaml
  - elastic_stack/elasticsearch/single-node/elasticsearch-sts.yaml

  - elastic_stack/kibana/kibana-svc.yaml
  - elastic_stack/kibana/kibana-deploy.yaml
```
</details>

### Blocking 

Currently blocked by the mount of specific certs on the odfe nodes when using a StatefulSet with 3 replicas, each node should mount the right certificate file from `odfe-ssl-certs` secret.

**Comment by xr09** [comment]
My current approach to solve this is to use an init container to parse the ordinal number of the StatefulSet and copy the right config file and certificate to a new volume, then mount the right files from this new volume into the final container.

**Comment by xr09** [comment]
Currently the ODFE cluster is running with a StatefulSet (3 replicas), the conf hack to mount each certificate on the right pod is working:

```yaml
      initContainers:
        - name: conf-hack
          image: 'frolvlad/alpine-bash'
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
          command:
            - bash
            - "-c"
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]]
              ordinal=${BASH_REMATCH[1]}
              number=$((1 + $ordinal))
              cp -n /ssl/node"$number".key /data/node.key
              cp -n /ssl/node"$number".pem /data/node.pem
              cp -n /conf/elasticsearch-node"$number".yml /data/elasticsearch.yml
          volumeMounts:
            - name: wazuh-elasticsearch-conf
              mountPath: /data
            - name: odfe-ssl-certs
              mountPath: /ssl
              readOnly: true
            - name: elastic-odfe-conf
              mountPath: /conf
              readOnly: true
```

**Comment by xr09** [comment]
Thanks to built-in env var rendering for the config file on the elastic/opendistro Docker entrypoint it is possible to avoid the `conf-hack` initContainer and ship a single config file able to scale.


```yaml
cluster:
  name: ${CLUSTER_NAME}
node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: 1
  attr.box_type: hot

network.host: ${NETWORK_HOST}

http:
  compression: true

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}
```

On the sts defnition:

```yaml
- name: CLUSTER_NAME
    value: wazuh
- name: NUMBER_OF_MASTERS
    value: "3"
- name: NODE_MASTER
    value: "true"
- name: NODE_INGEST
    value: "true"
- name: NODE_DATA
    value: "true"
- name: NETWORK_HOST
    value: "0.0.0.0"
- name: NODE_NAME
    valueFrom:
    fieldRef:
        fieldPath: metadata.name
- name: DISCOVERY_SERVICE
    value: wazuh-elasticsearch
- name: KUBERNETES_NAMESPACE
    valueFrom:
    fieldRef:
        fieldPath: metadata.namespace
```




Also switched to use a simpler script (based on openssl) to generate the certs offline.

**Comment by xr09** [comment]
This issue is deprecated by latest developments since we switched to use a single certificate in all nodes.
