### ISSUE TITLE
Fix migration procedure from 4.3 to 4.4

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-kubernetes#353]
### Description
Some users are having issues upgrading from `4.3` to `4.4` due to some changes in the certificate paths.
We should contemplate these changes in the upgrade documentation.

### Tasks
- [x] Provide an updated upgrade procedure
- [x] Test the procedure
- [x] Provide evidence of the test

**Comment by c-bordon** [comment]
## Upgrade report:
Some observations about the deploy documentation:

- This part of the documentation is confusing to me:
https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/kubernetes-deployment.html#setup-ssl-certificates

![image](https://github.com/wazuh/wazuh-kubernetes/assets/64099752/483a26d1-960b-4d2c-8f5b-332e6e86d180)

I interpreted that I had to add this to the kustomization.yaml file inside envs/eks, since after creating the certificates there is no need to modify anything

- I tried to do a test with the following version of kubectl and I got some errors:

```console
kubectl version --output=yaml
clientVersion:
  buildDate: "2023-04-15T02:14:53Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-15T00:33:09Z"
  compiler: gc
  gitCommit: 4a3479673cb6d9b63f1c69a67b57de30a4d9b781
  gitTreeState: clean
  gitVersion: v1.26.4-eks-0a21954
  goVersion: go1.19.8
  major: "1"
  minor: 26+
  platform: linux/amd64
```

I had to change to the next version in order to create the cluster correctly: 

```console
./kubectl version --output=yaml
clientVersion:
  buildDate: "2021-06-16T12:59:11Z"
  compiler: gc
  gitCommit: 092fbfbf53427de67cac1e9fa54aaa09a28371d7
  gitTreeState: clean
  gitVersion: v1.21.2
  goVersion: go1.16.5
  major: "1"
  minor: "21"
  platform: linux/amd64
serverVersion:
  buildDate: "2023-04-15T00:33:09Z"
  compiler: gc
  gitCommit: 4a3479673cb6d9b63f1c69a67b57de30a4d9b781
  gitTreeState: clean
  gitVersion: v1.26.4-eks-0a21954
  goVersion: go1.19.8
  major: "1"
  minor: 26+
  platform: linux/amd64

WARNING: version difference between client (1.21) and server (1.26) exceeds the supported minor version skew of +/-1

```

**Comment by c-bordon** [comment]
## Update report:

- After carrying out some tests in Kubernetes 1.26, some problems were detected in the creation of the PVs, they were reported in this [issue](https://github.com/wazuh/wazuh-kubernetes/issues/355), I am going to check which version we have this problem with to clarify it in our documentation

- It is necessary to update the documentation clarifying 2 possible paths to follow before updating the cluster:

  1. If no changes have been made in the manifests, the upgrade process can be done simply by performing a `git checkout` to the tag to which you want to update and then doing a `kubectl apply`, with this the cluster would be updated without problems

  2. If we have changes in the manifests, what we must do is make some additional changes before performing the upgrade:
  
  Files to update:
   - `wazuh/indexer_stack/wazuh-dashboard/dashboard-deploy.yaml`
    line: 
     - 35: `image: 'wazuh/wazuh-dashboard:4.4.x'`
     - 46: `mountPath: /usr/share/wazuh-dashboard/certs/cert.pem`
     - 50: `mountPath: /usr/share/wazuh-dashboard/certs/key.pem`
     - 54: `mountPath: /usr/share/wazuh-dashboard/certs/root-ca.pem`
     - 86: `value: /usr/share/wazuh-dashboard/certs/cert.pem`
     - 88: `value: /usr/share/wazuh-dashboard/certs/key.pem`
   - `wazuh/indexer_stack/wazuh-dashboard/dashboard_conf/opensearch_dashboards.yml`
    line: 
     - 10: `server.ssl.key: "/usr/share/wazuh-dashboard/certs/key.pem"'`
     - 11: `server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/cert.pem"`
     - 12: `opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/root-ca.pem"]`
   - `wazuh/indexer_stack/wazuh-indexer/cluster/indexer-sts.yaml`
    line: 
     - 62: `image: 'wazuh/wazuh-indexer:4.4.x'`
     - 93: `mountPath: /usr/share/wazuh-indexer/certs/node-key.pem`
     - 97: `mountPath: /usr/share/wazuh-indexer/certs/node.pem`
     - 101: `mountPath: /usr/share/wazuh-indexer/certs/root-ca.pem`
     - 105: `mountPath: /usr/share/wazuh-indexer/certs/admin.pem`
     - 109: `mountPath: /usr/share/wazuh-indexer/certs/admin-key.pem`
     - 113: `mountPath: /usr/share/wazuh-indexer/opensearch.yml`
     - 117: `/usr/share/wazuh-indexer/opensearch-security/internal_users.yml`
   - `wazuh/indexer_stack/wazuh-indexer/indexer_conf/opensearch.yml`
    line: 
     - 11: `plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem`
     - 12: `plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem`
     - 13: `plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem`
     - 14: `plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem`
     - 15: `plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem`
     - 16: `plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem`
   - `wazuh/wazuh_managers/wazuh-master-sts.yaml`
    line: 
     - 44: `image: 'wazuh/wazuh-manager:4.4.x'`
   - `wazuh/wazuh_managers/wazuh-worker-sts.yaml`
    line: 
     - 47: `image: 'wazuh/wazuh-manager:4.4.x'`

**Comment by c-bordon** [comment]
PR in documentation repository: https://github.com/wazuh/wazuh-documentation/pull/6111
