### ISSUE TITLE
Support new stage RC 2 for 4.5.1 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kubernetes#433]
## Description

This issue attempts to support a new stage RC 2 for 4.5.1 in the wazuh-kubernetes repository.

## Tasks

- [x] Change revision to `40502`. https://github.com/wazuh/wazuh-kubernetes/pull/434
- [x] Change revision to `40503`. https://github.com/wazuh/wazuh-kubernetes/pull/435
- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-rc2 from branch 4.5.1 on wazuh-kubernetes repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.5.1-rc2

**Comment by davidcr01** [comment]
Done. Also removed v4.5.1 tag and pre-release.

**Comment by teddytpc1** [comment]
Reviewed.

**Comment by teddytpc1** [comment]
Reviewed.

**Comment by teddytpc1** [comment]
Reviewed.
