### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#445]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh-kubernetes repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh-kubernetes repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.6.0-alpha1.

**Comment by teddytpc1** [comment]
Reviewed.
