### ISSUE TITLE
Support new stage RC 2 for 4.5.2 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#450]
## Description

This issue attempts to support a new stage RC 2 for 4.5.2 in the wazuh-kubernetes repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2 (if applicable).
- [x] Bump revision for branch 4.5.2 on wazuh-kubernetes repository. https://github.com/wazuh/wazuh-kubernetes/pull/451
- [x] Create tag v4.5.2-rc2 from branch 4.5.2 on wazuh-kubernetes repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.5.2-rc2.

**Comment by juliamagan** [comment]
Missing changes in release:

![image](https://github.com/wazuh/wazuh-kubernetes/assets/80041853/207e0c12-3e0d-43c7-bb54-8efc8b6b5800)

**Comment by juliamagan** [comment]
LGTM
