### ISSUE TITLE
Support new stage RC 2 for 4.5.3 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-kubernetes#468]
## Description

This issue attempts to support a new stage RC 2 for 4.5.3 in the wazuh-kubernetes repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] Bump revision for branch 4.5.3 on wazuh-kubernetes repository. https://github.com/wazuh/wazuh-kubernetes/pull/469
- [x] Create tag v4.5.3-rc2 from branch 4.5.3 on wazuh-kubernetes repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.5.3-rc2.
