### ISSUE TITLE
Support new stage Alpha 1 for 4.7.0 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#483]
## Description

This issue attempts to support a new stage Alpha 1 for 4.7.0 in the wazuh-kubernetes repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.0 (if applicable).
- [ ] Bump revision for branch 4.7.0 on wazuh-kubernetes repository.
- [ ] Create tag v4.7.0-alpha1 from branch 4.7.0 on wazuh-kubernetes repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.0-alpha1.

**Comment by juliamagan** [comment]
LGTM
