### ISSUE TITLE
Support new stage RC 2 for 4.7.1 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-kubernetes#538]
## Description

This issue attempts to support a new stage RC 2 for 4.7.1 in the wazuh-kubernetes repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.1 (if applicable).
- [ ] Bump revision for branch 4.7.1 on wazuh-kubernetes repository.
- [ ] Create tag v4.7.1-rc2 from branch 4.7.1 on wazuh-kubernetes repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.1-rc2.
