### ISSUE TITLE
Mounting /etc/postfix causes the override of that path in the pod.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-kubernetes#55]
Hi team,

When mounting a volume in /etc/postfix like in:

https://github.com/wazuh/wazuh-kubernetes/blob/f1f3ad1747237a8ed1781c53f3ce1ff9b25215ab/wazuh_managers/wazuh-master-sts.yaml#L51-L52

If the volume is empty, will cause the override of the content saved in that path. In order to avoid that, it's required to implement a mechanism in our Docker images https://github.com/wazuh/wazuh-docker/issues/240 that copies the content from another path, this way we avoid the override while still being able to load configurations.

In order to fix this, the following task must be done:

### Tasks:

- [ ]  Add new path to Wazuh Manager statefulsets

- [ ] Deploy with the new configuration and check if the content from the volume is mounted without overriding.

- [ ] Test the postfix service after loading custom configuration

Best regards,

Jose

**Comment by manuasir** [comment]
Since we decided to get the Postfix deps out of the Wazuh main container, this issue is not related anymore. The changes will be out with the v4.0 release. More info: https://github.com/wazuh/wazuh-docker/issues/277
