### ISSUE TITLE
Support new stage RC 1 for 4.7.2 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#552]
## Description

This issue attempts to support a new stage RC 1 for 4.7.2 in the wazuh-kubernetes repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.2 (if applicable).
- [ ] Bump revision for branch 4.7.2 on wazuh-kubernetes repository.
- [ ] Create tag v4.7.2-rc1 from branch 4.7.2 on wazuh-kubernetes repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.2-rc1.
