### ISSUE TITLE
Support new stage Beta 2 for 4.8.0 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#600]
## Description

This issue attempts to support a new stage Beta 2 for 4.8.0 in the wazuh-kubernetes repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-kubernetes repository.
- [ ] Create tag v4.8.0-beta2 from branch 4.8.0 on wazuh-kubernetes repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.8.0-beta2.
