### ISSUE TITLE
Support new stage RC 1 for 4.7.5 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#680]
## Description

This issue attempts to support a new stage RC 1 for 4.7.5 in the wazuh-kubernetes repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.5 (if applicable).
- [x] Bump revision for branch 4.7.5 on wazuh-kubernetes repository. https://github.com/wazuh/wazuh-kubernetes/pull/685
- [x] Change docker image tag in docker-compose to tag v4.7.5-rc1 in branch 4.7.5. https://github.com/wazuh/wazuh-kubernetes/pull/686
- [x] Create tag v4.7.5-rc1 from branch 4.7.5 on wazuh-kubernetes repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.5-rc1.
- [x] Change docker image tag in docker-compose back to 4.7.5 in branch 4.7.5. https://github.com/wazuh/wazuh-kubernetes/pull/687

**Comment by c-bordon** [comment]
LGTM
