### ISSUE TITLE
Support new stage RC 2 for 4.7.5 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-kubernetes#693]
## Description

This issue attempts to support a new stage RC 2 for 4.7.5 in the wazuh-kubernetes repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.5 (if applicable).
- [ ] Bump revision for branch 4.7.5 on wazuh-kubernetes repository.
- [ ] Change docker image tag in docker-compose to tag v4.7.5-rc2 in branch 4.7.5
- [ ] Create tag v4.7.5-rc2 from branch 4.7.5 on wazuh-kubernetes repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.7.5-rc2.
- [ ] Change docker image tag in docker-compose back to 4.7.5 in branch 4.7.5

**Comment by c-bordon** [comment]
LGTM
