### ISSUE TITLE
Wazuh Kubernetes Release 3.11.3_7.5.2

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-kubernetes#74]
Wazuh version: 3.11.3
Elastic version: 7.5.2

### Tasks

- [ ] Adapt to new versions (3.11.3 - 7.5.2)

- [ ] Check templates and update them if needed

- [ ] Tests

- [ ] Update changelog

- [ ] Tag: v3.11.3_7.5.2

- [ ] Update documentation references

- [ ] Draft release
