### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-kubernetes repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-kubernetes#873]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-kubernetes repository.

## Tasks

- [x] ~~Delete previous RC 1 release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.9.2-rc1.~~
- [x] ~~Delete previous v4.9.2-rc1 tag.~~
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-kubernetes repository. https://github.com/wazuh/wazuh-kubernetes/pull/874
- [x] Change the docker image tags in kubernetes manifests to tag v4.9.2-rc1 in branch 4.9.2. https://github.com/wazuh/wazuh-kubernetes/pull/875
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-kubernetes repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-kubernetes/releases/tag/v4.9.2-rc1.
- [x] Change docker image tags in kubernetes manifests back to 4.9.2 in branch 4.9.2. https://github.com/wazuh/wazuh-kubernetes/pull/876

**Comment by c-bordon** [comment]
LGTM
