### ISSUE TITLE
Wazuh Kubernetes v3.13.1_7.8.0

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-kubernetes#94]
Wazuh version: 3.13.1
Elastic version: 7.8.0

### Tasks

- [x] Adapt to new versions (3.13.1 - 7.8.0)

- [x] Check templates and update them if needed

- [ ] Tests

- [ ] Update changelog

- [ ] Tag: v3.13.1_7.8.0

- [ ] Update documentation references

- [ ] Draft release
